version: "3"

services:
  client:
    container_name: frontend
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/data
    environment:
      - API_URL=http://localhost:8081/
  server:
    build: ./backend
    ports:
      - 8081:8081
    volumes:
      - ./backend:/data
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db